name: Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  check_suite:
    types: [completed]
  status: {}
  workflow_dispatch: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automerge when checks pass
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: ""
          UPDATE_METHOD: rebase
          MERGE_RETRY_SLEEP: "10000"
          MERGE_FORKS: "false"
